-- local path = require "plenary.path"
-- local ui = vim.ui
-- local fn = vim.fn
-- local api = vim.api
-- local cmd = vim.cmd
-- local uv = vim.loop
--
-- local M = {}

-- function M.writeCreatingDirs(dir, confirm)
-- 	-- <afile> refers to the file we are saving
-- 	-- :p is a modifier that expands to full filename
-- 	-- :h is a modifier that removes the file from full filename
-- 	-- :t is a modifier that generates the filename with extension (Good to know)
-- 	dir = fn:expand("<afile>:p:h")
-- 	-- This handles URLs using netrw. See ':help netrw-transparent' for details.
-- 	if dir:find("%l+://") == 1 then
-- 		return
-- 	end
--
-- 	if fn:isdirectory(dir) == 0 then -- I don't know what I'm doing :)
-- 		-- use the "vim.ui.select" spicy look <3
-- 		confirm = fn:confirm("Create a new directory", "&Yes\n&No")
-- 		if confirm == 1 then
-- 			fn:mkdir(dir, "p") -- "p" is the flag that will create all the parent directories
-- 		end
-- 	end
-- end

-- from CosmicNvim
-- function M.get_relative_path(file_path)
-- 	local plenary_path = require("plenary.path")
-- 	local parsed_path, _ = file_path:gsub("file://", "")
-- 	local path = plenary_path:new(parsed_path)
-- 	local relative_path = path:make_relative(uv.cwd())
-- 	return "./" .. relative_path
-- end

-- return M
